import { Achievement } from "./types";

export const achievements: ReadonlyArray<Achievement> = (
  [
    [1, "JELLY", "500w10sec"],
    [2, "MASTER DRAFTSMAN", "Drafting"],
    [3, "WHOA NELLY", "30mphTrike"],
    [4, "SPEED DEMON", "40mphBike"],
    [5, "DAREDEVIL", "50mphRocket"],
    [6, "CAN'T STOP NOW", "Distance10"],
    [8, "SPRINTER APPRENTICE", "Watt1"],
    [9, "LIT", "Watt2"],
    [10, "CIRCUIT BREAKER", "Watt3"],
    [11, "JUST SCRAPE IT", "Watt4"],
    [12, "THE BLOWDRIER", "Watt5"],
    [13, "PREMIER POWER", "Watt6"],
    [14, "OFF THE ROCKS", "Watt7"],
    [15, "1.21 GIGAWATTS", "Watt8"],
    [16, "MARATHONER", "Distance40km"],
    [17, "100 CLICKS", "Distance100km"],
    [18, "NO BIG DEAL", "Distance100mi"],
    [22, "HABITUAL", "Ride3days"],
    [23, "ADDICTED", "Ride7Days"],
    [24, "WORKING FROM HOME", "Ride14days"],
    [25, "YOU'RE POPULAR", "GetRideOn1"],
    [26, "YOU'RE FAMOUS", "GetRideOn2"],
    [27, "BIGGER THAN JENSIE!", "GetRideOn3"],
    [28, "PAPARAZZI", "Fanview"],
    [29, "INTO THE WIND", "Uturn"],
    [30, "RIDE ON", "GiveRideOn1"],
    [31, "BIG FAN", "GiveRideOn2"],
    [32, "FAN CLUB", "GiveRideOn3"],
    [34, "STATISTICIAN", "ConnectToStrava"],
    [35, "PAIRED", "PairZwift"],
    [37, "SWEAT!", "CompleteWorkout"],
    [38, "100KPH!", "100kph"],
    [39, "WARMED UP", "VolcanoLap01"],
    [40, "HOTHEAD", "VolcanoLap02"],
    [41, "ON FIRE!", "VolcanoLap03"],
    [42, "HOT OFF THE LINE", "SessionRun1mi"],
    [43, "FIRST FIVE", "SessionRun5k"],
    [44, "GIMMIE TEN", "SessionRun10k"],
    [45, "RUNNERS DOZEN", "SessionRun13mi"],
    [46, "GOING THE DISTANCE", "SessionRun26mi"],
    [47, "CENTURION", "DistanceRun100"],
    [48, "STREET CRED", "DistanceRun500"],
    [49, "PURSUIT OF HAPPINESS", "DistanceRun1000"],
    [50, "EARNING THE DONUTS", "MileRun9min"],
    [51, "LEG WARMER", "MileRun8min"],
    [52, "LIKE THE WIND", "MileRun7min"],
    [53, "ENGINES ARE GO", "MileRun6min"],
    [54, "OLYMPIAN", "MileRun5min"],
    [55, "EVERESTED!", "EverestChallenge"],
    [56, "AVID CLIMBER", "ClimbAlpe5x"],
    [57, "MASOCHIST", "ClimbAlpe25x"],
    [58, "LIFTOFF!", "ClimbAlpe1hour"],
    [59, "2018 UCI WORLDS SHORT LAP", "RouteComplete"],
    [60, "INNSBRUCKRING", "RouteComplete"],
    [61, "ACHTERBAHN", "RouteComplete"],
    [62, "LONDON LOOP", "RouteComplete"],
    [63, "GREATER LONDON FLAT", "RouteComplete"],
    [64, "LONDON CLASSIQUE", "RouteComplete"],
    [65, "LONDON 8", "RouteComplete"],
    [66, "SURREY HILLS", "RouteComplete"],
    [67, "PARK PERIMETER LOOP", "RouteComplete"],
    [68, "KNICKERBOCKER", "RouteComplete"],
    [69, "ASTORIA LINE 8", "RouteComplete"],
    [70, "EVERYTHING BAGEL", "RouteComplete"],
    [71, "GRAND CENTRAL CIRCUIT", "RouteComplete"],
    [72, "2015 UCI WORLDS COURSE", "RouteComplete"],
    [73, "COBBLED CLIMBS", "RouteComplete"],
    [74, "THE FAN FLATS", "RouteComplete"],
    [75, "HILLY ROUTE", "RouteComplete"],
    [76, "SAND AND SEQUOIAS", "RouteComplete"],
    [77, "VOLCANO CIRCUIT", "RouteComplete"],
    [78, "VOLCANO CLIMB", "RouteComplete"],
    [79, "THREE SISTERS", "RouteComplete"],
    [80, "2019 UCI WORLDS HARROGATE CIRCUIT", "RouteComplete"],
    [81, "QUEEN'S HIGHWAY", "RouteComplete"],
    [82, "DUCHY ESTATE", "RouteComplete"],
    [83, "ROYAL PUMP ROOM 8", "RouteComplete"],
    [84, "THE PRETZEL", "RouteComplete"],
    [85, "JUNGLE CIRCUIT", "RouteComplete"],
    [86, "ROAD TO SKY", "RouteComplete"],
    [87, "FOUR HORSEMEN", "RouteComplete"],
    [88, "TOUR OF FIRE AND ICE", "RouteComplete"],
    [89, "BIG LOOP", "RouteComplete"],
    [90, "MOUNTAIN ROUTE", "RouteComplete"],
    [91, "MOUNTAIN 8", "RouteComplete"],
    [92, "FIGURE 8", "RouteComplete"],
    [93, "FIGURE 8 REVERSE", "RouteComplete"],
    [94, "FLAT ROUTE", "RouteComplete"],
    [95, "ROAD TO RUINS", "RouteComplete"],
    [96, "THE MEGA PRETZEL", "RouteComplete"],
    [97, "VOLCANO CIRCUIT CCW", "RouteComplete"],
    [98, "VOLCANO FLAT", "RouteComplete"],
    [99, "OUT AND BACK AGAIN", "RouteComplete"],
    [100, "TEMPUS FUGIT", "RouteComplete"],
    [101, "THE UBER PRETZEL", "RouteComplete"],
    [102, "BIGGER LOOP", "RouteComplete"],
    [103, "TICK TOCK", "RouteComplete"],
    [104, "WHOLE LOTTA LAVA", "RouteComplete"],
    [105, "MUIR AND THE MOUNTAIN", "RouteComplete"],
    [106, "BIG FOOT HILLS", "RouteComplete"],
    [107, "DUST IN THE WIND", "RouteComplete"],
    [108, "QUATCH QUEST", "RouteComplete"],
    [109, "GREATER LONDON 8", "RouteComplete"],
    [110, "THE LONDON PRETZEL", "RouteComplete"],
    [111, "THE PRL HALF", "RouteComplete"],
    [112, "GREATEST LONDON FLAT", "RouteComplete"],
    [113, "THE PRL FULL", "RouteComplete"],
    [114, "GREATER LONDON LOOP", "RouteComplete"],
    [115, "GREATEST LONDON LOOP", "RouteComplete"],
    [116, "TRIPLE LOOPS", "RouteComplete"],
    [117, "KNICKERBOCKER REVERSE", "RouteComplete"],
    [118, "LADY LIBERTY", "RouteComplete"],
    [119, "MIGHTY METROPOLITAN", "RouteComplete"],
    [120, "RISING EMPIRE", "RouteComplete"],
    [121, "THE 6 TRAIN", "RouteComplete"],
    [122, "THE HIGHLINE", "RouteComplete"],
    [123, "LUTSCHER", "RouteComplete"],
    [124, "LUTSCHER CCW", "RouteComplete"],
    [125, "TOUR OF TEWIT WELL", "RouteComplete"],
    [126, "11.1 OCEAN BLVD", "RouteComplete"],
    [127, "5K LOOP", "RouteComplete"],
    [128, "CHILI PEPPER", "RouteComplete"],
    [129, "JON'S ROUTE", "RouteComplete"],
    [130, "THAT'S AMORE", "RouteComplete"],
    [131, "COUCH TO SKY K", "RouteComplete"],
    [132, "FLAT IRONS", "RouteComplete"],
    [133, "HUDSON ROLL", "RouteComplete"],
    [134, "PARK TO PEAK", "RouteComplete"],
    [135, "SHUMAN TRAIL LOOP", "RouteComplete"],
    [136, "MAY FIELD", "RouteComplete"],
    [137, "R.G.V.", "RouteComplete"],
    [138, "DOUCE FRANCE", "RouteComplete"],
    [139, "CASSE PATTES", "RouteComplete"],
    [140, "ROULE MA POULE", "RouteComplete"],
    [141, "PETIT BOUCLE", "RouteComplete"],
    [142, "TIRE BOUCHON", "RouteComplete"],
    [143, "VEN-TOP", "RouteComplete"],
    [144, "CHAMPS-ÉLYSÉES", "RouteComplete"],
    [145, "LUTECE EXPRESS", "RouteComplete"],
    [146, "BEACH ISLAND LOOP", "RouteComplete"],
    [147, "OCEAN LAVA CLIFFSIDE LOOP", "RouteComplete"],
    [148, "SERPENTINE 8", "RouteComplete"],
    [149, "TWO BRIDGES LOOP", "RouteComplete"],
    [150, "SEA TO TREE", "RouteComplete"],
    [151, "KAPPA QUEST", "RouteComplete"],
    [152, "CHAIN CHOMPER", "RouteComplete"],
    [153, "COUNTRYSIDE TOUR", "RouteComplete"],
    [154, "FLATLAND LOOP", "RouteComplete"],
    [155, "TWO VILLAGE LOOP", "RouteComplete"],
    [156, "SPIRIT FOREST", "RouteComplete"],
    [157, "THREE VILLAGE LOOP", "RouteComplete"],
    [158, "KAPPA QUEST REVERSE", "RouteComplete"],
    [159, "SUKI'S PLAYGROUND", "RouteComplete"],
    [160, "VALLEY TO MOUNTAINTOP", "RouteComplete"],
    [161, "FARMLAND LOOP", "RouteComplete"],
    [162, "CLIMBER'S GAMBIT", "RouteComplete"],
    [163, "LEGENDS AND LAVA", "RouteComplete"],
    [164, "RAILWAYS AND ROOFTOPS", "RouteComplete"],
    [165, "ROOFTOP RENDEZVOUS", "RouteComplete"],
    [166, "NEON FLATS", "RouteComplete"],
    [167, "SPRINTER'S PLAYGROUND", "RouteComplete"],
    [168, "NEOKYO ALL-NIGHTER", "RouteComplete"],
    [169, "SLEEPLESS CITY", "RouteComplete"],
    [170, "WANDERING FLATS", "RouteComplete"],
    [171, "TEMPLES AND TOWERS", "RouteComplete"],
    [172, "TWILIGHT HARBOR", "RouteComplete"],
    [173, "CHASING THE SUN", "RouteComplete"],
    [174, "ELECTRIC LOOP", "RouteComplete"],
    [175, "CASTLE TO CASTLE", "RouteComplete"],
    [176, "NEOKYO CRIT COURSE", "RouteComplete"],
    [177, "THREE LITTLE SISTERS", "RouteComplete"],
    [178, "TRIPLE FLAT LOOPS", "RouteComplete"],
    [179, "DOWNTOWN TITANS", "RouteComplete"],
    [180, "EASTERN EIGHT", "RouteComplete"],
    [181, "MAYAN BRIDGE LOOP", "RouteComplete"],
    [182, "ITALIAN VILLAS CIRCUIT", "RouteComplete"],
    [183, "HANDFUL OF GRAVEL (CYCLING)", "RouteComplete"],
    [184, "HANDFUL OF GRAVEL (RUNNING)", "RouteComplete"],
    [185, "SURFIN' SAFARI", "RouteComplete"],
    [186, "SPLASH AND DASH", "RouteComplete"],
    [194, "MECH ISLE LOOP", "RouteComplete"],
    [195, "BRIDGES AND BOARDWALKS", "RouteComplete"],
    [196, "ISLAND HOPPER", "RouteComplete"],
    [197, "FINE AND SANDY", "RouteComplete"],
    [198, "ISLAND OUTSKIRTS", "RouteComplete"],
    [199, "MAKURI 40", "RouteComplete"],
    [200, "COUNTRY TO COASTAL", "RouteComplete"],
    [201, "TURF N SURF", "RouteComplete"],
    [202, "LA REINE", "RouteComplete"],
    [203, "GOTHAM GRIND", "RouteComplete"],
    [204, "WATOPIA'S WAISTBAND", "RouteComplete"],
    [205, "RICHMOND UCI REVERSE", "RouteComplete"],
    [206, "ROLLING HIGHLANDS", "RouteComplete"],
    [207, "CITY AND THE SGURR", "RouteComplete"],
    [208, "GLASGOW CRIT CIRCUIT", "RouteComplete"],
    [209, "LOCH LOOP", "RouteComplete"],
    [210, "THE MUCKLE YIN", "RouteComplete"],
    [211, "Portal Climber", "ClimbPortal1x"],
    [212, "Climb Portal Pro", "ClimbPortal10x"],
    [213, "Legs of Steel", "ClimbPortal25x"],
    [214, "COAST CRUSHER", "RouteComplete"],
    [215, "THE BIG RING", "RouteComplete"],
    [216, "ACCELERATE TO ELEVATE", "RouteComplete"],
    [217, "SHORELINES AND SUMMITS", "RouteComplete"],
    [218, "SUGAR COOKIE", "RouteComplete"],
    [219, "GOING COASTAL", "RouteComplete"],
    [220, "TEMPLE TREK", "RouteComplete"],
    [221, "CANOPIES AND COASTLINES", "RouteComplete"],
    [222, "REPACK RUSH", "RouteComplete"],
    [223, "SPIRAL INTO THE VOLCANO", "RouteComplete"],
    [224, "BIG FLAT 8", "RouteComplete"],
    [225, "CASTLE CRIT", "RouteComplete"],
    [226, "CASTLE CRIT (RUNNING)", "RouteComplete"],
    [227, "LOOP DE LOOP", "RouteComplete"],
    [228, "MOUNTAIN MASH", "RouteComplete"],
    [229, "ZWIFT GAMES 2024 EPIC", "RouteComplete"],
    [230, "JURASSIC COAST", "RouteComplete"],
    [231, "PARTY ON!", "GetRideOn1"],
    [232, "QUEEN'S HIGHWAY AFTER PARTY", "RouteComplete"],
    [233, "HILLY ROUTE REVERSE", "RouteComplete"],
    [234, "LONDON CLASSIQUE REVERSE", "RouteComplete"],
    [235, "PARK PERIMETER REVERSE", "RouteComplete"],
    [236, "OH HILL NO", "RouteComplete"],
    [237, "COASTAL CROWN LOOP", "RouteComplete"],
    [238, "GLYPH HEIGHTS", "RouteComplete"],
    [239, "MAYAN MASH", "RouteComplete"],
    [240, "TIDES AND TEMPLES", "RouteComplete"],
    [241, "RADIO RENDEZVOUS", "RouteComplete"],
    [242, "PEAK PERFORMANCE", "RouteComplete"],
    [243, "SNOWMAN", "RouteComplete"],
    [244, "POWER TO THE TOWER", "RouteComplete"],
    [245, "NAVIG8", "RouteComplete"],
    [246, "MAYAN SAN REMO", "RouteComplete"],
    [247, "ITZA CLIMB FINISH", "RouteComplete"],
    [248, "ITZA PARTY", "RouteComplete"],
    [249, "MAYAN 8", "RouteComplete"],
    [250, "ELEVATION EVALUATION", "RouteComplete"],
    [251, "TITAN'S RUN", "RouteComplete"],
    [252, "EPIC RUN", "RouteComplete"],
    [253, "HILLY ROUTE REVERSE RUN", "RouteComplete"],
    [254, "MECH ISLE LOOP RUN", "RouteComplete"],
    [255, "CHAMPS-ÉLYSÉES RUN", "RouteComplete"],
    [256, "LUTECE EXPRESS RUN", "RouteComplete"],
    [257, "COBBLED CLIMBS RUN", "RouteComplete"],
    [258, "QUEEN'S HIGHWAY RUN", "RouteComplete"],
    [259, "GLASGOW CRIT CIRCUIT RUN", "RouteComplete"],
    [260, "LOCH LOOP RUN", "RouteComplete"],
    [261, "LIBBY HILL AFTER PARTY", "RouteComplete"],
    [262, "RICHMOND LOOP AROUND", "RouteComplete"],
    [263, "YORKSHIRE DOUBLE LOOP", "RouteComplete"],
    [264, "SHISA SHAKEDOWN", "RouteComplete"],
    [265, "MAKURI PRETZEL", "RouteComplete"],
    [266, "BRAEK-FAST CRITS AND GRITS", "RouteComplete"],
    [267, "DECA DASH", "RouteComplete"],
    [268, "WAISTED 8", "RouteComplete"],
    [269, "LOOPIN LAVA", "RouteComplete"],
    [270, "THE CLASSIC", "RouteComplete"],
    [271, "COAST TO COAST", "RouteComplete"],
    [272, "TRIPLE TWIST", "RouteComplete"],
    [273, "THE CLASSIC RUN", "RouteComplete"],
    [274, "OUTER SCOTLAND", "RouteComplete"],
    [275, "PETITE DOULEUR", "RouteComplete"],
    [276, "LONDON FLAT", "RouteComplete"],
    [277, "TAIR DRINGFA FECHAN", "RouteComplete"],
    [278, "NYC KOM AFTER PARTY", "RouteComplete"],
    [279, "THE MAGNIFICENT 8", "RouteComplete"],
    [280, "MAKURI MADNESS", "RouteComplete"],
    [281, "SCOTLAND SMASH", "RouteComplete"],
    [282, "DOWNTOWN ERUPTION", "RouteComplete"],
    [283, "LONDON UPRISING", "RouteComplete"],
    [284, "ZG25 QUEEN", "RouteComplete"],
    [285, "DANGER NOODLE", "RouteComplete"],
    [286, "HILLTOP HUSTLE", "RouteComplete"],
    [287, "LAGUARDIA AFTER PARTY", "RouteComplete"],
    [288, "NEON AFTER PARTY", "RouteComplete"],
    [289, "VEN-10", "RouteComplete"],
    [290, "CROISSANT", "RouteComplete"],
    [291, "THREE MUSKETEERS", "RouteComplete"],
    [292, "GENTIL 8", "RouteComplete"],
    [293, "BON VOYAGE", "RouteComplete"],
    [294, "HELL OF THE NORTH", "RouteComplete"],
    [295, "KNIGHTS OF THE ROUNDABOUT", "RouteComplete"],
    [296, "SACRE BLEU", "RouteComplete"],
    [297, "MACARON", "RouteComplete"],
    [298, "VEN-10 RUN", "RouteComplete"],
    [299, "RAPIDE RUN", "RouteComplete"],
    [300, "RED ZONE REPEATS", "RouteComplete"],
    [301, "POWER PUNCHES", "RouteComplete"],
    [302, "CLIMB CONTROL", "RouteComplete"],
    [303, "FLAT OUT FAST", "RouteComplete"],
    [304, "WATTS OF THE WILD", "RouteComplete"],
    [305, "TROPIC RUSH", "RouteComplete"],
    [306, "LONDON CALLING", "RouteComplete"],
    [307, "DÙN DASH", "RouteComplete"],
    [308, "ELECTRIC BREAK", "RouteComplete"],
    [309, "SCOTLAND AFTER PARTY", "RouteComplete"],
    [310, "HIGHLAND RUN", "RouteComplete"],
    [311, "TRACK MEET", "RouteComplete"],
    [312, "YORU RUN", "RouteComplete"],
    [313, "GLASGOW CRIT SIX", "RouteComplete"],
    [314, "HOT LAPS", "RouteComplete"],
    [315, "WATTS THE LIMIT", "RouteComplete"],
    [316, "TIMES SQUARE CIRCUIT", "RouteComplete"],
    [317, "DOUBLE SPAN SPIN", "RouteComplete"],
    [318, "PROSPECT PARK LOOP", "RouteComplete"],
    [319, "GREEN TO SCREEN", "RouteComplete"],
    [320, "NO SLEEP TILL BROOKLYN", "RouteComplete"],
    [321, "DOUBLE PARKED", "RouteComplete"],
    [322, "STAY PUFT PURSUIT", "RouteComplete"],
    [323, "FUHGEDDABOUDIT", "RouteComplete"],
    [324, "SPINFINITY", "RouteComplete"],
    [325, "THE DOUBLE BOROUGH", "RouteComplete"],
    [326, "SPINFINITY ULTRA", "RouteComplete"],
    [327, "THE GREENWAY", "RouteComplete"],
    [328, "TOEFIELD TORNADO", "RouteComplete"],
    [329, "AVON FLYER", "RouteComplete"],
    [330, "ISSENDORF EXPRESS", "RouteComplete"],
    [331, "PROSPECT PARK LOOP RUN", "RouteComplete"],
    [332, "TIMES SQUARE CIRCUIT RUN", "RouteComplete"],
    [333, "TOEFIELD TORNADO RUN", "RouteComplete"],
    [334, "AVON FLYER RUN", "RouteComplete"],
    [335, "INNSBRUCK KOM AFTER PARTY", "RouteComplete"],
    [336, "RICHMOND ROLLERCOASTER", "RouteComplete"],
    [337, "EMPIRE ELEVATION", "RouteComplete"],
    [338, "KAZE KICKER", "RouteComplete"],
    [339, "HUDSON HUSTLE", "RouteComplete"],
    [340, "COBBLED CROWN", "RouteComplete"],
    [341, "PEAKY PAVE", "RouteComplete"],
    [342, "THREE STEP SISTERS", "RouteComplete"],
    [343, "THE EPILOCH", "RouteComplete"],
    [344, "NEON SHORE LOOP", "RouteComplete"],
    [345, "SOUTHERN COAST CRUISE", "RouteComplete"],
    [346, "JARVIS SEASIDE SPRINT", "RouteComplete"],
    [347, "ZWIFT ROAD ACADEMY 2020 MEN'S", "zam2020_badge"],
    [348, "ZWIFT ROAD ACADEMY 2020 WOMEN'S", "zaw2020_badge"],
    [349, "ZWIFT RUN ACADEMY 2020", "zarun2020_badge"],
    [350, "QA CAMPAIGN SERVICE 1 14 1", "QACS_badge"],
    [351, "ZWIFT TRIATHLON ACADEMY 2020", "zatri2020_badge"],
    [352, "TOUR DE ZWIFT 2021 RIDE", "tdz2021ride_badge"],
    [353, "TOUR DE ZWIFT 2021 RUN", "tdz2021run_badge"],
    [354, "HAUTE ROUTE 2021", "hauteroute2021_badge"],
    [355, "TOUR OF WATOPIA 2021 RUN", "tow2021run_badge"],
    [356, "TOUR OF WATOPIA 2021 RIDE", "tow2021ride_badge"],
    [357, "ADIDAS RUN FOR THE OCEANS", "rfto2021_badge"],
    [358, "OFF THE MAAP 2021", "offthemaap2021_badge"],
    [359, "ZWIFT ACADEMY ROAD 2021", "zar2021_badge"],
    [360, "ZWIFT ACADEMY RUN 2021", "zarun2021_badge"],
    [361, "ZWIFT ACADEMY TRIATHLON 2021", "zatri2021_badge"],
    [362, "NEOKYO BADGE HUNTING SERIES", "neokyobadge_badge"],
    [363, "CAMPAIGN SERVICES 1 8 0", "CS180_badge"],
    [364, "TOUR DE ZWIFT 2022 RIDE", "tdz2022ride_badge"],
    [365, "TOUR DE ZWIFT 2022 RUN", "tdz2022run_badge"],
    [366, "WAHOO CLIMBING MISSION", "wahooclimbmission_badge"],
    [367, "RAPHA RISING CAMPAIGN 2022", "rapharising_badge"],
    [368, "TOUR OF WATOPIA 2022 RIDE CAMPAIGN", "tow2022ride_badge"],
    [369, "TOUR OF WATOPIA 2022 RUN CAMPAIGN", "tow2022run_badge"],
    [370, "TOUR DE FRANCE FEMME AVEC ZWIFT APRIL MISSION", "newrules_badge"],
    [371, "ADIDAS RUN FOR THE OCEANS 2022", "rfto22_badge"],
    [372, "KASK PROTONE ICON MISSION", "kask2022_badge"],
    [373, "WTF MISSION", "wtfmission_badge"],
    [374, "OFF THE MAAP 2022", "otm22_badge"],
    [375, "GET ROLLING", "zracing22_badge"],
    [376, "ZWIFT ACADEMY ROAD 2022", "zar2022_badge"],
    [377, "RACE LIKE A CHAMP 2022", "zracingoct2022_badge"],
    [378, "TUNE UP MISSION", "octmission2022_badge"],
    [379, "ZWIFT ACADEMY TRI", "zatri2022_badge"],
    [380, "RACE MAKURI", "zracingnov2022_badge"],
    [381, "JOIN THE PARTY MISSION", "novmission2022_badge"],
    [382, "TOUR OF MAKURI ISLANDS", "tomi2022_badge"],
    [383, "ZWIFT PRO TRAINING CAMP", "zprotraining_badge"],
    [384, "K'S FOR DAYS MISSION", "decmission2022_badge"],
    [385, "RACE LIKE A PRO", "zracingdec2022_badge"],
    [386, "FLAT IS FAST 2023", "zracingjan2023_badge"],
    [387, "FIT FAST", "janmission2023_badge"],
    [388, "TOUR DE ZWIFT 2023 RIDE", "tdz2023ride_badge"],
    [389, "TOUR DE ZWIFT 2023 RUN", "tdz2023run_badge"],
    [390, "SKY'S THE LIMIT", "febmission2023_badge"],
    [391, "RACE SCOTLAND", "zracingfeb2023_badge"],
    [392, "ZWIFT ACADEMY RUN 2023", "zarun2023_badge"],
    [393, "QA INVISIBLE CAMPAIGN", "qaic_badge"],
    [394, "FIVING AND THRIVING", "marmission2023_badge"],
    [395, "RACE LONDON", "zracingmar2023_badge"],
    [396, "TOUR OF WATOPIA 2023 RUN", "tow2023run_badge"],
    [397, "TOUR OF WATOPIA 2023 RIDE", "tow2023ride_badge"],
    [398, "COBBLE CRUSHER", "zracingapr2023_badge"],
    [399, "CONQUER A CLASSIC", "aprmission2023_badge"],
    [400, "ZWIFT SPRING TRAINING 2023", "zst2023_badge"],
    [401, "CRIT CLUB", "zracingmay2023_badge"],
    [402, "WORK IT OUT", "maymission2023_badge"],
    [403, "TEST ACMS 1", "testacms1_badge"],
    [404, "PRIDE ON", "junmission2023_badge"],
    [405, "OG RACING", "zracingjun2023_badge"],
    [406, "ZRS COASTAL CRUISE", "zrs2023_badge"],
    [407, "CLIMB PORTAL FIRST ASCENT CHALLENGE", "climbportal2023_badge"],
    [408, "CLIMB TOURMALET", "julmission2023_badge"],
    [409, "BEACH PARTY", "zracingjul2023_badge"],
    [410, "ZRS WATCH THE FEMMES", "julyzrs2023_badge"],
    [411, "RACE THE WORLDS", "zracingaug2023_badge"],
    [412, "ZRS PODIUM RIDES", "augustzrs2023_badge"],
    [413, "CHASING RAINBOWS", "augmission2023_badge"],
    [414, "GET ROLLING AGAIN", "zracingsep2023_badge"],
    [415, "ZRS PRETZELFEST", "septemberzrs2023_badge"],
    [416, "OMNIUM", "sepmission2023_badge"],
    [417, "RACE WATOPIA", "zracingoct2023_badge"],
    [418, "TOUR OF WATOPIA RIDE", "towfall2023ride_badge"],
    [419, "WANDER WATOPIA", "octmission2023_badge"],
    [420, "TOUR OF WATOPIA RUN", "towfall2023run_badge"],
    [421, "NEOKYO NIGHTS", "zracingnov2023_badge"],
    [422, "ZRS WORLD TOUR", "novemberzrs2023_badge"],
    [423, "ZWIFT ACADEMY 2023", "za2023_badge"],
    [424, "KOM CHALLENGE", "novmission2023_badge"],
    [425, "BEST OF", "zracingdec2023_badge"],
    [426, "ZRS REWIND", "decemberzrs2023_badge"],
    [427, "END OF YEAR EPIC", "decmission2023_badge"],
    [428, "FLAT IS FAST 2024", "zracingjan2024_badge"],
    [429, "TOUR DOWN UNDER", "janmission2024_badge"],
    [430, "TOUR DE ZWIFT 2024 RIDE", "tdz2024ride_badge"],
    [431, "TOUR DE ZWIFT 2024 RUN", "tdz2024run_badge"],
    [432, "RACE LIKE A CHAMP 2024", "zracingfeb2024_badge"],
    [433, "FIND YOUR FITNESS", "febmission2024_badge"],
    [434, "ZWIFT GAMES", "zg2024ride_badge"],
    [435, "ASCEND THE ALPE", "marmission2024_badge"],
    [436, "THE ZWIFT BIG SPIN 2024", "tbs2024ride_badge"],
    [437, "LAP IT UP", "zracingapr2024_badge"],
    [438, "CENTURY CHALLENGE", "aprmission2024_badge"],
    [439, "SPRING TRAINING 2024", "springtraining2024_badge"],
    [440, "MT FUJI", "maymission2024_badge"],
    [441, "BAG THAT BADGE", "zracingmay2024_badge"],
    [442, "NEW HORIZONS", "junmission2024_badge"],
    [443, "SEA BREEZE", "zracingjun2024_badge"],
    [444, "CLIMB PORTAL CHALLENGE", "climbportal2024_badge"],
    [445, "VIVE LA FRANCE", "zracingjul2024_badge"],
    [446, "TOUR DE FRANCE", "julmission2024_badge"],
    [447, "PUNCHY POWER", "zracingaug2024_badge"],
    [448, "FEMMES FINALE", "augmission2024_badge"],
    [449, "ZWIFT ACADEMY 2024", "zwiftacademy2024_badge"],
    [450, "ROUTE HUNTER", "sepmission2024_badge"],
    [451, "PINARELLO POWERED", "zracingsep2024_badge"],
    [452, "WATOPIA ORIGINS", "octmission2024_badge"],
    [453, "COMMUNITY RACING FESTIVAL", "zracingoct2024_badge"],
    [454, "TOUR OF WATOPIA 2024", "tow2024ride_badge"],
    [455, "TRAIN TOGETHER", "novmission2024_badge"],
    [456, "ZWIFT CAMP BASELINE", "zwiftcampbaseline2024_badge"],
    [457, "FRESH OUTTA 24", "zracingdec2024_badge"],
    [458, "FLAT IS FAST 2025", "zracingjan2025_badge"],
    [459, "TOUR DE ZWIFT", "tourdezwift2025ride_badge"],
    [460, "TOUR DE ZWIFT RUN 2025", "tourdezwift2025run_badge"],
    [
      461,
      "TOUR DE ZWIFT 2025 STAGE MASTER CHALLENGE",
      "tourdezwift2025challenge_badge",
    ],
    [462, "SHIMANO FIND YOUR FAST", "zracingfeb2025_badge"],
    [463, "ZWIFT GAMES", "zwiftgames2025_badge"],
    [464, "THE ZWIFT BIG SPIN", "zwiftbigspin2025_badge"],
    [465, "AFTER PARTY", "zracingapr2025_badge"],
    [466, "ZWIFT CAMP INSIDE OUT", "zwiftcampinsideout2025_badge"],
    [467, "MAKURI MAY", "zracingmay2025_badge"],
    [468, "CITYSCAPES", "zracingjun2025_badge"],
    [469, "ALLEZ ALLEZ ALLEZ", "zracingjul2025_badge"],
    [470, "KICK N SPRINT", "zracingaug2025_badge"],
    [471, "ROLLING WITH ENVE", "zracingsep2025_badge"],
    [472, "RED ROCK LOOP", "RouteComplete"],
    [473, "RED ROCK RUN", "RouteComplete"],
    [474, "RED ROCK LOOP ARCADE", "RouteComplete"],
    [475, "YUMEZI GRIT", "RouteComplete"],
    [476, "RED ROCK LOOP REVERSE", "RouteComplete"],
  ] as const
).map(([id, name, imageName]) => ({ id, name, imageName }));
